version: "2"
services:
  postgresql:
    image: bitnami/postgresql:15
    labels:
      org.springframework.boot.service-connection: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411