services:
  otelcol:
    image: otel/opentelemetry-collector-contrib
    restart: on-failure
    volumes:
    - ./docker/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
    - '4317:4317'
    - '4318:4318'
    extra_hosts:
    - 'host.docker.internal:host-gateway'
  lognroll:
    image: ghcr.io/making/lognroll:native
    ports:
    - '14318:4318'
  zipkin:
    image: ghcr.io/openzipkin-contrib/zipkin-otel:main
    ports:
    - '9411:9411'
    environment:
      UI_ENABLED: 'true'
  blog-db:
    image: 'bitnami/postgresql:16'
    labels:
      org.springframework.boot.service-connection: postgres
    restart: on-failure
    ports:
    - '5432:5432'
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
