kind: Service
apiVersion: v1
metadata:
  name: blog-api-service
  namespace: blog
  labels:
    app: blog-api
spec:
  selector:
    app: blog-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-api
  namespace: blog
  labels:
    app: blog-api
spec:
  replicas: 2
  revisionHistoryLimit: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-api
      annotations:
        kubernetes.io/change-cause: "FIXME"
    spec:
      containers:
      - name: blog-api
        image: asia.gcr.io/fe-tmaki/blog-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: _JAVA_OPTIONS
          value: "-Xmx304M -Xss1M -XX:MaxMetaspaceSize=145M -XX:ReservedCodeCacheSize=240M -XX:CompressedClassSpaceSize=24M -XX:MaxDirectMemorySize=10M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: blog-db-secret
              key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-db-secret
              key: mysql-password
        - name: SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-username
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-password
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server-service:8888
        - name: SPRING_CLOUD_CONFIG_USERNAME
          valueFrom:
            secretKeyRef:
              name: config-server-secret
              key: config-server-user
        - name: SPRING_CLOUD_CONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-server-secret
              key: config-server-password
        - name: INFO_DOCKER_DIGEST
          value: "_INFO_DOCKER_DIGEST"
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3