apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certificate
  namespace: blog
spec:
  secretName: certificate-tls
  issuerRef:
    name: letsencrypt-ik-am
    kind: ClusterIssuer
  dnsNames:
  - '*.ik.am'