receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: 'blog-api'
        scrape_interval: 30s
        static_configs:
        - targets: [ 'host.docker.internal:8080' ]
        metrics_path: /actuator/prometheus

exporters:
  debug:
    verbosity: detailed
  otlphttp/zipkin:
    endpoint: http://zipkin:9411
    tls:
      insecure: true
  otlphttp/lognroll:
    endpoint: http://lognroll:4318
    tls:
      insecure: true
    headers:
      Authorization: Bearer changeme

service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - otlphttp/zipkin
    logs:
      receivers:
      - otlp
      exporters:
      - otlphttp/lognroll