receivers:
  otlp:
    protocols:
      grpc: { }
      http: { }
  prometheus:
    config:
      scrape_configs:
      - job_name: 'blog-api'
        scrape_interval: 30s
        static_configs:
        - targets: [ 'host.docker.internal:8080' ]
        metrics_path: /actuator/prometheus
processors:
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  otlp/uptrace:
    endpoint: http://uptrace:14317
    tls: { insecure: true }
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14318?grpc=14317' }
  prometheusremotewrite/uptrace:
    endpoint: 'http://uptrace:14318/api/v1/prometheus/write'
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14318?grpc=14317' }

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/uptrace ]
    metrics:
      receivers: [ otlp, prometheus ]
      processors: [ batch ]
      exporters: [ otlp/uptrace ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/uptrace ]