apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: blog-api
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/categolj/blog-api
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: JAVA_TOOL_OPTIONS
    value: -XX:ReservedCodeCacheSize=32M -Xss512k -Dfile.encoding=UTF-8 -Dmanagement.health.probes.enabled=true -Dmanagement.endpoint.health.probes.add-additional-paths=true
  - name: BPL_JVM_THREAD_COUNT
    value: "28"
  - name: SPRING_SECURITY_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: admin-password
        name: blog-config
  - name: BLOG_GITHUB_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        key: github-access-token
        name: blog-config
  - name: BLOG_GITHUB_WEBHOOK_SECRET
    valueFrom:
      secretKeyRef:
        key: github-webhook-secret
        name: blog-config
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: "8081"
      prometheus.io/scrape: "true"
  - name: api_descriptor
    value:
      description: Blog Entry API
      location:
        path: /v3/api-docs
      owner: making
      system: blog
      type: openapi
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  resources:
    limits:
      memory: 320Mi
    requests:
      memory: 320Mi
  serviceClaims:
  - name: blog-db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: blog-db

