apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: blog-api
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
  name: blog-api
spec:
  image: ghcr.io/categolj/blog-api:jvm
  env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: blog-db
  - name: logging.level.io.opentelemetry.exporter.zipkin.ZipkinSpanExporter
    value: ERROR
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: "8081"
      prometheus.io/scrape: "true"
  - name: api_descriptor
    value:
      description: Blog Entry API
      location:
        path: /v3/api-docs
      owner: making
      type: openapi
      system: blog