name: CI
on:
  push:
    branches:
    - rsocket
  pull_request:
    branches:
    - rsocket
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -e
        ./mvnw -V test
    - name: mvn spring-boot:build-image
      if: github.ref == 'refs/heads/rsocket'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g' |  tr -d '\t')
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        IMAGE_NAME=${DOCKER_REGISTRY}:${VERSION}
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./mvnw -V spring-boot:build-image -Dspring-boot.build-image.imageName=${IMAGE_NAME} -Dmaven.test.skip=true -Dspring-boot.version=${BOOT_VERSION}
        docker push ${IMAGE_NAME}

    - uses: azure/k8s-set-context@v1
      if: github.ref == 'refs/heads/rsocket'
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: k14s/setup-k14s-action@v1
      if: github.ref == 'refs/heads/rsocket'
    - name: kubectl apply
      if: github.ref == 'refs/heads/rsocket'
      env:
        WAIT_UNTIL_READY_SELECTOR: app=blog-rsocket
      run: |
        set -e
        ytt \
          -f k8s/app.yml \
          -f k8s/pdb.yml \
          -f k8s/route-definition.yml \
          -f k8s/overlays/disable-wavefront.yml \
          | kbld -f - \
          | kubectl apply -f -
        wget -q https://raw.githubusercontent.com/zlabjp/kubernetes-resource/master/assets/common.sh
        source common.sh
        wait_until_pods_ready 120 5 ${WAIT_UNTIL_READY_SELECTOR}
