name: CI
on:
  push:
    branches:
    - rsocket
  pull_request:
    branches:
    - rsocket
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - name: Cache Maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Unit Test
      env:
        DATABASE_URL: postgresql://postgres:testdb@localhost:5432/blog_test
      run: |
        set -e
        
        docker run -d \
          --name postgres \
          -e "POSTGRES_DB=blog_test" \
          -e "POSTGRES_PASSWORD=testdb" \
          -e "TZ=Japan" \
          -v $(pwd):/tmp \
          -p 5432:5432 \
          postgres:9.6.10
        
        until nc -z $(docker inspect --format='{{.NetworkSettings.IPAddress}}' postgres) 5432
        do
          echo "waiting for postgres container..."
          sleep 0.5
        done
        
        docker exec postgres \
          psql -U postgres -d blog_test -f /tmp/src/main/resources/schema.sql
        
        ./mvnw test
