name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
jobs:
  test:
    uses: making/workflows/.github/workflows/maven-unit-test.yaml@main
  build-jvm-image:
    needs: test
    uses: making/workflows/.github/workflows/build-docker-image-maven-jvm.yaml@main
    with:
      image_file: image.yaml
  build-native-image:
    needs: test
    uses: making/workflows/.github/workflows/build-docker-image-maven-native.yaml@main
    with:
      image_file: image_native.yaml
  save-image-jvm:
    if: github.ref == 'refs/heads/main'
    needs: build-jvm-image
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      target: image.yaml
  save-image-native:
    if: github.ref == 'refs/heads/main'
    needs: build-native-image
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      target: image_native.yaml