name: CI
on:
  push:
    branches:
    - rsocket
  pull_request:
    branches:
    - rsocket
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '15.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -e
        ./mvnw -V test
    - name: mvn spring-boot:build-image
      if: github.ref == 'refs/heads/rsocket'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g' |  tr -d '\t')
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        IMAGE_NAME=${DOCKER_REGISTRY}:${VERSION}
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./mvnw -V spring-boot:build-image -Dspring-boot.build-image.imageName=${IMAGE_NAME} -Dmaven.test.skip=true -Dspring-boot.version=${BOOT_VERSION}
        docker push ${IMAGE_NAME}
        docker pull ${IMAGE_NAME}
        cat <<EOF > values.yml
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        git_repo: https://github.com/categolj/blog-api
        git_commit: $(git rev-parse HEAD)
        image_digest: $(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_NAME} | awk -F '@' '{print $2}')
        EOF
        cat values.yml
    - name: send a pull request to dev
      if: github.ref == 'refs/heads/rsocket'
      env:
        REPOSITORY: making/config
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE: master
      run: |
        set -ex
        GIT_REV=$(git rev-parse HEAD)
        BRANCH_NAME="update-blog-api-dev-${GIT_REV}"
        COMMIT_MESSAGE="[Dev] Bump to categolj/blog-api@${GIT_REV}"
        mkdir -p ~/.ssh
        cat > ~/.ssh/config <<EOF
        StrictHostKeyChecking no
        LogLevel quiet
        EOF
        cat > ~/.ssh/id_rsa <<EOF
        ${GIT_SSH_KEY}
        EOF
        chmod 0600 ~/.ssh/*

        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        git clone git@github.com:${REPOSITORY}.git
        cd $(echo ${REPOSITORY} | awk -F '/' '{print $2}')
        git checkout -b ${BRANCH_NAME}
        mv ../values.yml home-lab/grape/app/blog-api/dev/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BRANCH_NAME}
        curl -u ${GIT_NAME}:${ACCESS_TOKEN} -H "Content-Type: application/json" -X POST -d "{\"title\":\"${COMMIT_MESSAGE}\",\"body\":\"See https://github.com/categolj/blog-api/commit/${GIT_REV}\",\"head\":\"${BRANCH_NAME}\",\"base\":\"${BASE}\"}" https://api.github.com/repos/${REPOSITORY}/pulls
    - name: send a pull request to prod
      if: github.ref == 'refs/heads/rsocket'
      env:
        REPOSITORY: making/config
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE: master
      run: |
        set -ex
        GIT_REV=$(git rev-parse HEAD)
        BRANCH_NAME="update-blog-api-prod-${GIT_REV}"
        COMMIT_MESSAGE="[Prod] Bump to categolj/blog-api@${GIT_REV}"

        cd ..
        rm -rf $(echo ${REPOSITORY} | awk -F '/' '{print $2}')
        git clone git@github.com:${REPOSITORY}.git
        cd $(echo ${REPOSITORY} | awk -F '/' '{print $2}')
        git checkout -b ${BRANCH_NAME}
        mv ../values.yml home-lab/grape/app/blog-api/prod/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BRANCH_NAME}
        curl -u ${GIT_NAME}:${ACCESS_TOKEN} -H "Content-Type: application/json" -X POST -d "{\"title\":\"${COMMIT_MESSAGE}\",\"body\":\"See https://github.com/categolj/blog-api/commit/${GIT_REV}\",\"head\":\"${BRANCH_NAME}\",\"base\":\"${BASE}\"}" https://api.github.com/repos/${REPOSITORY}/pulls