name: CI
on:
  push:
    branches:
    - rsocket
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - rsocket
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.1.0
        native-image: true
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      env:
        _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
      run: |
        set -e
        ./mvnw -V test
    - name: mvn deploy
      if: github.ref == 'refs/heads/rsocket'
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' | xargs echo)
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
               <id>sonatype-snapshots</id>
               <username>${SONATYPE_USERNAME}</username>
               <password>${SONATYPE_PASSWORD}</password>
            </server>
          </servers>
        </settings>
        EOF
        sed -i 's|</project>|<distributionManagement><repository><id>sonatype-snapshots</id><name>sonatype-snapshots</name><url>https://oss.sonatype.org/content/repositories/snapshots</url></repository></distributionManagement></project>|' pom.xml
        ./mvnw -V package -s settings.xml -P native,mostly-static -DskipTests=true -Dspring-boot.version=${BOOT_VERSION}
        ./mvnw -V deploy:deploy-file -DskipTests -Pnative -s settings.xml -DrepositoryId=sonatype-snapshots -Durl=https://oss.sonatype.org/content/repositories/snapshots
    - name: mvn spring-boot:build-image
      if: github.ref == 'refs/heads/deprecated'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g' |  tr -d '\t')
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        IMAGE_NAME=${DOCKER_REGISTRY}:${VERSION}
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./mvnw -V spring-boot:build-image -Dspring-boot.build-image.imageName=${IMAGE_NAME} -Dmaven.test.skip=true -Dspring-boot.version=${BOOT_VERSION}
        docker push ${IMAGE_NAME}
        docker pull ${IMAGE_NAME}
        cat <<EOF > values.yml
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        git_repo: https://github.com/categolj/blog-api
        git_commit: $(git rev-parse HEAD)
        image_name: ${IMAGE_NAME}
        image_digest: $(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_NAME} | awk -F '@' '{print $2}')
        EOF
        cat values.yml
    - name: update config
      if: github.ref == 'refs/heads/deprecated'
      env:
        REPOSITORY: making/config
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE: master
        APP_NAME: blog-api
      run: |
        set -ex
        GIT_REV=$(git rev-parse HEAD)
        COMMIT_MESSAGE="[Dev] Bump to categolj/${APP_NAME}@${GIT_REV}"
        mkdir -p ~/.ssh
        cat > ~/.ssh/config <<EOF
        StrictHostKeyChecking no
        LogLevel quiet
        EOF
        cat > ~/.ssh/id_rsa <<EOF
        ${GIT_SSH_KEY}
        EOF
        chmod 0600 ~/.ssh/*

        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        git clone git@github.com:${REPOSITORY}.git
        cd $(echo ${REPOSITORY} | awk -F '/' '{print $2}')

        # Update dev directly
        cp ../values.yml home-lab/grape/app/${APP_NAME}/dev/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BASE}
        DEV_REV=$(git rev-parse HEAD)

        # send a pull request to prod
        BRANCH_NAME="update-${APP_NAME}-prod-${GIT_REV}"
        COMMIT_MESSAGE="[Prod] Bump to categolj/${APP_NAME}@${GIT_REV}"
        git checkout -b ${BRANCH_NAME}
        cp ../values.yml home-lab/grape/app/${APP_NAME}/prod/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BRANCH_NAME}
        curl -u ${GIT_NAME}:${ACCESS_TOKEN} -H "Content-Type: application/json" -X POST -d "{\"title\":\"${COMMIT_MESSAGE}\",\"body\":\"See https://github.com/categolj/${APP_NAME}/commit/${GIT_REV}\nCorresponding commit to dev env is ${DEV_REV}\",\"head\":\"${BRANCH_NAME}\",\"base\":\"${BASE}\"}" https://api.github.com/repos/${REPOSITORY}/pulls
